## This is only a single container right now but in future this should bring up supporting services needed for development ie: postgres, audit service ect.
version: '3'
services:
  reviewer-submission:
    image: node:12-alpine@sha256:5646d1e5bc470500414feb3540186c02845db0e0e1788621c271fbf3a0c1830d
    ports:
      - "3000:3000"
    working_dir: "/src"
    healthcheck:
      test: "curl localhost:3000/health"
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["sh", "-c", "yarn && yarn run start:dev"]
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      S3_AWS_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_FORCE_PATH_STYLE: 'true'
      S3_FILE_BUCKET: test
      NEW_RELIC_HOME: /etc/reviewer/
      MAX_QL_COMPLEXITY: 100
      MAX_QL_DEPTH: 5
      MAX_FILE_SIZE_IN_BYTES: 100000000
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      USER_ADAPTER_URL: http://reviewer-mocks:3003/current-user
      SCIENCE_BEAM_URL: http://reviewer-mocks:3003/science-beam/convert"
      SCIENCE_BEAM_TIMEOUT: 20000
    volumes:
      - ./config:/etc/reviewer
      - ./:/src/:z
    networks:
      - "reviewer"

  postgres:
    image: liberoadmin/reviewer-xpub-postgres:latest
    container_name: test_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
    networks:
      - "reviewer"
      
  s3:
    image: minio/minio:latest
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  reviewer:
    external:
      name: "reviewer"
