version: '3'
services:
  # base container
  submission_typescript:
    build:
      context: "."
      dockerfile: "Dockerfile.typescript"
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_submission_typescript:${IMAGE_TAG}

  # Server
  submission_application:
    build:
      context: "."
      dockerfile: 'Dockerfile.application'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_submission_application:${IMAGE_TAG}
    networks:
      - 'reviewer_build'

networks:
  reviewer_build:
    external:
      name: reviewer_build
