version: '3'
services:
  reviewer-submission:
    build:
      context: "."
      dockerfile: 'Dockerfile'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer-submission:${IMAGE_TAG}
