## This is only a single container right now but in future this should bring up supporting services needed for development ie: postgres, audit service ect.
version: "3"
services:
  reviewer-submission:
    image: libero/reviewer-submission:${IMAGE_TAG:-local}
    container_name: test_reviewer-submission
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      # NEW_RELIC_LOG_ENABLED: "false"
      NEW_RELIC_NO_CONFIG_FILE: "true"
      CONFIG_PATH: /etc/reviewer/config.json
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      S3_AWS_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_FORCE_PATH_STYLE: 'true'
      S3_FILE_BUCKET: test
      NEW_RELIC_HOME: /etc/reviewer/
      MAX_QL_COMPLEXITY: 100
      MAX_QL_DEPTH: 5
      MAX_FILE_SIZE_IN_BYTES: 100000000
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      USER_ADAPTER_URL: http://reviewer-mocks:3003/current-user
      SCIENCE_BEAM_URL: http://reviewer-mocks:3003/science-beam/convert"
      SCIENCE_BEAM_TIMEOUT: 20000
    volumes:
      - ./tests/config/reviewer-submission.json:/etc/reviewer/config.json
      - ./tests/config/reviewer-submission-client.json:/etc/reviewer/config.client.json
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost ${SERVER_PORT:-3000}'
      interval: 3s
      timeout: 10s
      retries: 3

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:latest
    container_name: test_reviewer_mocks
    ports:
      - "${REVIEWER_MOCKS_PORT:-3003}:3003"
    environment:
      DATA_DIRECTORY_PATH: "/etc/mock-data/"
    volumes:
      - ./tests/config/reviewer-mocks.json:/etc/reviewer/config.json:z
      - ./tests/mock-data:/etc/mock-data/
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost ${REVIEWER_MOCKS_PORT:-3003}'
      interval: 3s
      timeout: 10s
      retries: 3

  s3:
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    container_name: test_s3
    ports:
      - "9004:9000"
    volumes:
      - ./tests/.minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 30s
      retries: 10

  s3_create-bucket:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add submission http://s3:9000 minio minio123;
      /usr/bin/mc rm -r --force submission/test;
      /usr/bin/mc mb submission/test;
      /usr/bin/mc policy set download submission/test;
      /usr/bin/mc policy set public submission/test;
      exit 0;
      "

  postgres:
    image: liberoadmin/reviewer-xpub-postgres:latest
    container_name: test_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
